config/routes.rb
Vedavaag::Application.routes.draw do

  resources :projects do
    get :approve, :on=>:member
  end

  resources :states do
    get :approve, :on=>:member
  end

 resources :generals

  resources :transactions do
    get :approve, :on=>:member
    get :text_report, :on=>:member
    get :approve_pay, :on=>:member
  end

  resources :accounts do
    post :csv_import, :on=>:collection
    get :approve, :on=>:member
    get :export, :on=>:collection

  end

  resources :roles

  resources :users do
    get :profile, :on=>:member
    get :update_profile, :on=>:member
    put :profile_update, :on=> :member
    get :change_password, :on=> :member
  end
  resources :user_sessions

  match 'login' => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  root :to => "user_sessions#new"
  match ':controller(/:action(/:id(.:format)))'
end

app/models/project.rb
class Project < ActiveRecord::Base

  #validations
  validates :name, :presence => true, :uniqueness => true, :length => {:maximum => 100}

  #search and recent
  class << self
    def recent
      order('created_at DESC').limit(4)
    end

    def search(query)
      if query
        where(:name.matches => "%#{query}%") #from meta_where gem
      else
        scoped
      end
    end

    def active
      where(:status => true).order('name ASC')
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :recent_items, :require_user
  filter_access_to :all
  layout "application", :except => [:show, :edit]

  def index
    @projects = Project.search(params[:search]).paginate(:page => page, :per_page => per_page).order("name ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @projects }
    end
  end

  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @project }
    end
  end

  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @project }
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to(projects_url, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.xml  { head :ok }
    end
  end
  def approve
    @project = Project.find(params[:id])
    @project.update_attribute('status', @project.status ? false : true)
    respond_to do |format|
      format.js
    end
  end

  ########################################################
  private
  def recent_items
    @recent = Project.recent
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="form-container">
  <p class="legend">
    <strong>Note:</strong>
    Required fields are marked with an asterisk (<em>*</em>)
  </p>
  <%= simple_form_for(@project, :validate => true) do |f| %>
      <fieldset>
        <%= f.input :name,:placeholder=>"Enter Project Name" %>
        <%= f.input :description %>
        <%= f.submit 'Save', :disable_with=>'Please wait...' %>
      </fieldset>
  <% end %>
</div>

app/views/projects/_recent.html.erb
<div class="recent_items">
  <div class="margin">
    <h3>Recent Projects</h3>
    <% if @recent.blank? %>
        No Projects Added Yet...
    <% else %>
        <% for project in @recent %>
            <div id="margin">
              <div class="left">&nbsp;</div>
              <div class="right">&nbsp;</div>
              <div class="left-to-right">
                <div class="pen">&nbsp;</div>
                <div class="text">
                  <%= link_to project.name, project_path(project), :class=>'usuallink tipTipRight',:rel=>"facebox",:title => "View Details" %>
                  <div style="margin: 8px 0px;">&nbsp;</div>
                </div>
              </div>
            </div>
        <% end %>
    <% end %>
    <div class="see_all">
      <a href="<%= projects_path %>">
        View all Projects
        <img hspace="2" border="0" alt="" src="/images/blue^.gif">
      </a>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<% title "Vedavaag | Projects" %>
<h3>Vedavaag | Projects | Manage Projects</h3>
<% content_for :left_panel do %>
    <td valign="top" width="250"> <%= render 'common/search' %>
      <%= render 'recent' %> </td>
<% end %>
<div class="help_text">
  Area for managing Projects. <br/>
  Along with creating, managing Projects for Application.
</div>
<div class="link_buttons">
  <%= link_to content_tag(:span, 'New Project'), new_project_path, :class => 'btn-blue' %>
</div>
<% if @projects.blank? %>
    <div class="error_msg">
      OOPS!.. No Projects are Found in the System..!
    </div>
<% else %>
    <table width="100%">
      <tr>
        <td align="right">
          <b><i>per page</i></b>
          <%= per_page %>| <%= page_entries_info @projects %>
        </td>
      </tr>
    </table>
    <table class="tablesorter">
      <thead>
      <tr>
        <th>#</th>
        <th>Status?</th>
        <th>Name</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% i=1 %>
      <% @projects.each do |project| %>
          <tr>
            <td><%= i %></td>
            <td>
              <div id="status_<%= project.id %>">
                <%= link_to project.status? ? image_tag('tick.gif') : image_tag('cross.gif'), approve_project_path(project), :remote => true %>
              </div>
            </td>
            <td><%= highlight(project.name,params[:search]) %></td>
            <td>
              <%= link_for_show_pop(project) %>
            </td>
          </tr>
          <% i = i + 1 %>
      <% end %>
      </tbody>
    </table>
    <div class="flickr_pagination">
      <%= page_entries_info @projects %> <%= will_paginate @projects, :container => false %>
    </div>

<% end %>

app/views/projects/new.html.erb
<% title "Vedavaag | Projects " %>
<% content_for :sub_heading do %>
    <%= sub_heading('Vedavaag | Projects','Create Project') %>
<% end %>
<div class="help_text_caution">
  FURTHER MODIFICATION WILL NOT POSSIBLE AFTER SUBMITTING THE FORM.
</div>
<%= render 'form',:heading => 'Create New Project' %>
<div class="link_buttons">
  <%=link_to_all(projects_path)%>
</div>

app/views/projects/show.html.erb
<div id="page_container">
  <div id="page_content">
    <div class="content">
      <h3>Projects | View Project Details</h3>

      <table width="100%" border=0 cellspacing=1 cellpadding=3 class="listTable">
        <tr>
          <th width="20%">Name</th>
          <td><%= @project.name %></td>
        </tr>
        <tr>
          <th width="20%">Description</th>
          <td><%= @project.description %></td>
        </tr>
      </table>
    </div>
  </div>
</div>