config/routes.rb
Vedavaag::Application.routes.draw do

  resources :projects do
    get :approve, :on=>:member
  end

  resources :states do
    get :approve, :on=>:member
  end

 resources :generals

  resources :transactions do
    get :approve, :on=>:member
    get :text_report, :on=>:member
    get :approve_pay, :on=>:member
  end

  resources :accounts do
    post :csv_import, :on=>:collection
    get :approve, :on=>:member
    get :export, :on=>:collection

  end

  resources :roles

  resources :users do
    get :profile, :on=>:member
    get :update_profile, :on=>:member
    put :profile_update, :on=> :member
    get :change_password, :on=> :member
  end
  resources :user_sessions

  match 'login' => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  root :to => "user_sessions#new"
  match ':controller(/:action(/:id(.:format)))'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_filter :recent_items, :require_user
  filter_access_to :all
  layout "application", :except => [:show]

  def index
    @transactions = Transaction.search(params[:search]).paginate(:page => page, :per_page => per_page) if has_any_role? :sa,:admin, :manager
    @transactions = Transaction.where(:requested_by=>current_user.id).search(params[:search]).paginate(:page => page, :per_page => per_page)  if has_role? (:employee)

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @transactions }
    end
  end

  def show
    @transaction = Transaction.find(params[:id])
  end

  def new
    @transaction = Transaction.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @transaction }
    end
  end

  def edit
    @transaction = Transaction.find(params[:id])
  end

  def create
    @transaction = Transaction.new(params[:transaction])
    @transaction.transaction_date= Time.now
    @transaction.requested_by =current_user.id
    @transaction.transaction_number = current_user.project.name.upcase+ '/' + '%03d' % current_user.id.to_s + '/' + Time.now.strftime('%m%d%H%M%S').to_s

    respond_to do |format|
      if @transaction.save

        #UserMailer.request_mail(@transaction,current_user).deliver

        format.html { redirect_to(transactions_path, :notice => 'Request was successfully created.') }
        format.xml { render :xml => @transaction, :status => :created, :location => @transaction }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @transaction = Transaction.find(params[:id])

    @transaction.payment_date= Time.now
    @transaction.payment_id =current_user.id
    @transaction.fund_status = true


    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])

        if @transaction.request_amount.to_f > params[:transaction][:paid_amount].to_f
          new_request_amount = @transaction.request_amount.to_f - params[:transaction][:paid_amount].to_f
          @new_request = Transaction.new(:request_amount=>new_request_amount,:transaction_date=>Time.now,:name=>@transaction.name,:description=>@transaction.description)
          @new_request.save
        else
          puts "NO"
        end

        format.html { redirect_to(transactions_path, :notice => 'Request was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to(transactions_url) }
      format.xml { head :ok }
    end
  end

  def approve
    @transaction = Transaction.find(params[:id])
    @transaction.update_attribute('approve_status', @transaction.approve_status ? false : true)
    @transaction.update_attribute('approved_by',current_user .id)
    @transaction.update_attribute('approve_date',Time.now)

    respond_to do |format|
      format.js
    end
  end
  def approve_pay
    @transaction = Transaction.find(params[:id])
    @transaction.update_attribute('fund_status', @transaction.fund_status ? false : true)
    @transaction.update_attribute('payment_by',current_user .id)
    @transaction.update_attribute('payment_date',Time.now)

    respond_to do |format|
      format.js
    end
  end


  ########################################################
  private
  def recent_items
    @recent = Transaction.recent if has_any_role? :admin,:sa,:manager
    @recent = Transaction.recent.where(:requested_by=>current_user.id) if has_role? (:employee)
  end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_edit_form.html.erb
<div class="form-container">
  <p class="legend">
    <strong>Note:</strong>
    Required fields are marked with an asterisk (<em>*</em>)
  </p>
  <%= simple_form_for(@transaction, :validate => true,:html => {:multipart => true }) do |f| %>
      <fieldset>
        <%= f.input :name,:label=>"Request Name",:placeholder=>"Request Name",:disabled=>true %>
        <%= f.input :description,:label=>"Request Description",:placeholder=>"Description of Request",:disabled=>true %>
        <%= f.input :request_amount,:label=>"Request Amount",:placeholder=>"Amount", :disabled=>true%>
        <%= f.input :remarks, :label=>"Remarks",:input_html => { :cols => 50, :rows => 3 },:disabled=>true %>
        <%= f.input :paid_amount,:label=>"Amount Approved",:placeholder=>"Amount Approved",:required=>true%>
        <%= f.input :payment_remarks, :label=>"Remarks" ,:required=>true%>

        <%= f.submit 'Save', :disable_with=>'Please wait...' %>
      </fieldset>
  <% end %>
</div>

app/views/transactions/_form.html.erb
<div class="form-container">
  <p class="legend">
    <strong>Note:</strong>
    Required fields are marked with an asterisk (<em>*</em>)
  </p>
  <%= simple_form_for(@transaction, :validate => true,:html => {:multipart => true }) do |f| %>
      <fieldset>
        <%= f.input :name,:label=>"Request Name",:placeholder=>"Request Name" %>
        <%= f.input :description,:label=>"Request Description",:placeholder=>"Description of Request" %>
        <%= f.input :request_amount,:label=>"Request Amount",:placeholder=>"Amount"%>
        <%= f.label :attachment, :label => 'Upload Attachment'  %>
        <%= f.file_field :attachment %>
        <%= f.input :remarks, :label=>"Remarks",:input_html => { :cols => 50, :rows => 3 } %>
        <%= f.submit 'Save', :disable_with=>'Please wait...' %>
      </fieldset>
  <% end %>
</div>

app/views/transactions/_recent.html.erb
<div class="recent_items">
  <div class="margin">
    <h3>Recent Requests</h3>
    <% if @recent.blank? %>
        No Requests Added Yet...
    <% else %>
        <% for transaction in @recent %>
            <div id="margin">
              <div class="left">&nbsp;</div>
              <div class="right">&nbsp;</div>
              <div class="left-to-right">
                <div class="pen">&nbsp;</div>
                <div class="text">
                  <%= link_to truncate(transaction.name.titleize, :length => 10), transaction_path(transaction), :class => 'usuallink tipTipRight', :title => "View Records" ,:rel=>"facebox"%>
                  <div style="margin: 8px 0px;">&nbsp;</div>
                </div>
              </div>
            </div>
        <% end %>
    <% end %>
    <div class="see_all">
      <a href="<%= transactions_path %>">
        View all Requests
        <img hspace="2" border="0" alt="" src="/images/blue^.gif">
      </a>
    </div>
  </div>
</div>

app/views/transactions/approve.js.erb
$("#status_<%=@transaction.id%>").html("<%=escape_javascript(link_to @transaction.approve_status? ? image_tag('tick.gif') : image_tag('cross.gif'),approve_transaction_path,:remote=>true)%>");

app/views/transactions/approve_pay.js.erb
$("#status_pay_<%=@transaction.id%>").html("<%=escape_javascript(link_to @transaction.fund_status ? image_tag('tick.gif') : image_tag('cross.gif'),approve_pay_transaction_path,:remote=>true)%>");

app/views/transactions/edit.html.erb
<% title "VEDAVAAG | Requests " %>
<% content_for :sub_heading do %>
    <%= sub_heading('VEDAVAAG | Requests','Update Request') %>
<% end %>
<div class="help_text">
  Area for Update Requests
</div>
<%= render 'edit_form' %>
<div class="link_buttons">
  <%=link_to_all(transactions_path)%>
</div>

app/views/transactions/index.html.erb
<% title "VEDAVAAG | Requests" %>
<h3>VEDAVAAG | Requests | Manage Requests</h3>

<% content_for :left_panel do %>
    <td valign="top" width="250"> <%= render 'common/search' %>
      <%= render 'recent' %> </td>
<% end %>
<div class="help_text">
  Area for managing Request. <br/>
  Along with creating, managing Requests.<br/>
</div>
<div class="link_buttons">
  <%= link_to content_tag(:span, 'New Request'), new_transaction_path, :class => 'btn-blue' if has_role? :employee %>
  <%= link_to content_tag(:span, 'All Requests'), transactions_path, :class => 'btn-yellow' %>
</div>

<% if @transactions.blank? %>
    <div class="error_msg">
      OOPS!.. No Requests are Found in the System..!
    </div>
<% else %>
    <table width="100%">
      <tr>
        <td align="right">
          <b><i>per page</i></b>
          <%= per_page %>| <%= page_entries_info @transactions %>
        </td>
      </tr>
    </table>
    <table class="tablesorter">
      <thead>
      <tr>
        <th>#</th>
        <th>Approve</th>
        <th>Payment</th>
        <th>Reference</th>
        <th>Date</th>
        <th>Name</th>
        <th>Description</th>
        <th>Amount</th>
        <th>Remarks</th>
        <% if has_any_role? :sa, :admin, :manager %>
            <th>Request By</th>
        <% end %>
        <th>Pay Date</th>

        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% i=1 %>
      <% @transactions.each do |transaction| %>
          <tr>
            <td><%= i %></td>
            <td>
              <% if has_any_role? :sa, :employee %>
                  <%= transaction.approve_status ? image_tag('tick.gif') : image_tag('cross.gif') %>
              <% else %>
                  <%= link_to_active(transaction, approve_transaction_path(transaction)) %>
              <% end %>
            </td>
            <td>
              <% if has_any_role? :sa, :employee, :admin, :manager %>
                  <%= transaction.fund_status ? image_tag('tick.gif') : image_tag('cross.gif') %>

              <% else %>
                  <%# link_to_active_pay(transaction, approve_pay_transaction_path(transaction)) %>
              <% end %>
            </td>
            <td><%= highlight(transaction.transaction_number, params[:search]) %></td>
            <td><%= transaction.transaction_date? ? transaction.transaction_date.strftime("%d-%m-%y") : "N.A" %></td>
            <td><%= truncate(transaction.name, :length => 10) %></td>
            <td><%= truncate(transaction.description, :length => 10) %></td>
            <td align="right"><%= number_with_precision(transaction.request_amount, :precision => 2) %></td>
            <td><%= transaction.remarks? ? (link_to "View", "#", :class => "tipTipRight", :title => transaction.remarks) : "N.A" %></td>
            <% if has_any_role? :sa, :admin, :manager %>
                <td><%= get_user(transaction) %></td>
            <% end %>
            <td><%= transaction.payment_date? ? transaction.payment_date.strftime("%d-%m-%y") : "N.A" %></td>

            <td>
              <%= link_for_show_pop(transaction) %>
              <% if transaction.fund_status? %>
              <% else %>
                  <%= link_for_edit(edit_transaction_path(transaction)) if has_role?(:manager) %>
              <% end %>
            </td>
          </tr>
          <% i = i + 1 %>
      <% end %>
      </tbody>
    </table>
    <div class="flickr_pagination">
      <%= page_entries_info @transactions %> <%= will_paginate @transactions, :container => false %>
    </div>
<% end %>

app/views/transactions/new.html.erb
<% title "VEDAVAAG | Requests " %>
<% content_for :sub_heading do %>
    <%= sub_heading('VEDAVAAG | Requests','Create Request') %>
<% end %>
<div class="help_text">
  Area for creating Requests. <br/>
  You can attache Excel sheet or Word file
</div>
<%= render 'form' %>
<div class="link_buttons">
  <%=link_to_all(transactions_path)%>
</div>

app/views/transactions/show.html.erb
<% title "VEDAVAAG | Request" %>
<div id="page_container">
  <div id="page_content">
    <div class="content">
      <h3>Request | View Request Details</h3>

      <table width="100%" border=0 cellspacing=1 cellpadding=3 class="listTable">
        <tr>
          <th width="20%">Reference</th>
          <td><%= @transaction.transaction_number %></td>
        </tr>
        <tr>
          <th width="20%">Name</th>
          <td><%= @transaction.name %></td>
        </tr>
        <tr>
          <th width="20%">Description</th>
          <td><%= @transaction.description %></td>
        </tr>
        <tr>
          <th width="20%">Request Amount</th>
          <td><%= number_with_precision(@transaction.request_amount, :precision => 2) %></td>
        </tr>
        <tr>
          <th width="20%">Request Date</th>
          <td><%= @transaction.transaction_date? ? @transaction.transaction_date.strftime("%d-%m-%y") : "N.A" %></td>
        </tr>
        <tr>
          <th width="20%">Approve Status</th>
          <td><%= @transaction.approve_status? ? "Approved" :"Pending" %></td>
        </tr>
        <tr>
          <th width="20%">Approve Date</th>
          <td><%= @transaction.approve_date? ? @transaction.approve_date.strftime("%d-%m-%y") : "N.A" %></td>
        </tr>
        <tr>
          <th width="20%">Payment Status</th>
          <td><%= @transaction.fund_status? ? "Approved" : "Pending" %></td>
        </tr>
        <tr>
          <th width="20%">Payment Date</th>
          <td><%= @transaction.payment_date? ? @transaction.payment_date.strftime("%d-%m-%y") : "N.A" %></td>
        </tr>
        <tr>
          <th width="20%">Remarks</th>
          <td><%= @transaction.remarks? ? @transaction.remarks : "--" %></td>
        </tr>
        <tr>
          <th width="20%">Attachment</th>
          <td>
            <% if @transaction.attachment.file? %>
            <%= link_to "Download", @transaction.attachment.url %>
            <% else %>
            N.A
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>