config/routes.rb
Vedavaag::Application.routes.draw do

  resources :projects do
    get :approve, :on=>:member
  end

  resources :states do
    get :approve, :on=>:member
  end

 resources :generals

  resources :transactions do
    get :approve, :on=>:member
    get :text_report, :on=>:member
    get :approve_pay, :on=>:member
  end

  resources :accounts do
    post :csv_import, :on=>:collection
    get :approve, :on=>:member
    get :export, :on=>:collection

  end

  resources :roles

  resources :users do
    get :profile, :on=>:member
    get :update_profile, :on=>:member
    put :profile_update, :on=> :member
    get :change_password, :on=> :member
  end
  resources :user_sessions

  match 'login' => "user_sessions#new", :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  root :to => "user_sessions#new"
  match ':controller(/:action(/:id(.:format)))'
end

app/models/account.rb
class Account < ActiveRecord::Base
  #validations
  validates :name, :presence => true
  validates :account_number,:presence => true,:uniqueness => true


  #Recent and Search
  class << self
    def recent
      order('id DESC').limit(4)
    end
    def search(query)
      if query
        where({:name.matches => "%#{query}%"} | {:account_number.matches => "%#{query}%"}) #from meta_where gem
      else
        scoped
      end
    end
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :recent_items, :require_user
  filter_access_to :all
  layout "application", :except => [:show]

  def index
    @accounts = Account.search(params[:search]).paginate(:page => page, :per_page => per_page)

  end

  def show
    @account = Account.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml { render :xml => @account }
    end
  end

  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @account }
    end
  end

  def edit
    @account = Account.find(params[:id])
  end

  def create
    @account = Account.new(params[:account])

    respond_to do |format|
      if @account.save
        format.html { redirect_to(@account, :notice => 'Account was successfully created.') }
        format.xml { render :xml => @account, :status => :created, :location => @account }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to(@account, :notice => 'Account was successfully updated.') }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to(accounts_url) }
      format.xml { head :ok }
    end
  end

  def approve
    @account = Account.find(params[:id])
    @account.update_attribute('status', @account.status ? false : true)
    respond_to do |format|
      format.js
    end

  end

  def upload
    render
  end

  def csv_import
    require 'csv'
    csv_file = params[:file]
    n=0
    CSV.new(csv_file.tempfile, :col_sep => ",").each do |row|
      transaction = Account.create do |tr|
        tr.name =row[0]
        tr.account_number = row[1]
        tr.bank_name = row[2]
        tr.branch_name = row[3]
      end
     transaction.save
      n = n + 1
    end
    flash[:notice]= "#{n} Accounts are imported successfully."
    respond_to do |format|
      format.html { redirect_to(accounts_path) }
      format.xml { head :ok }
    end
  end
  def export
    @accounts = Account.all
    html = render_to_string :layout => false
    kit = PDFKit.new(html, :page_size => 'A4')
    send_data(kit.to_pdf, :filename => "Account_Statement.pdf", :type => 'application/pdf')

  end

  ########################################################
  private
  def recent_items
    @recent = Account.recent
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<div class="form-container">
  <p class="legend">
    <strong>Note:</strong>
    Required fields are marked with an asterisk (<em>*</em>)
  </p>
  <%= simple_form_for(@account, :validate => true) do |f| %>
      <fieldset>
        <%= f.input :name,:label=>"Full Name",:placeholder=>"Account Holder Name" %>
        <%= f.input :account_number,:label=>"Account Number",:placeholder=>"Account Number" %>
        <%= f.input :bank_name,:label=>"Bank",:placeholder=>"Name of the Bank" %>
        <%= f.input :branch_name,:label=>"Branch",:placeholder=>"Branch" %>
        <%= f.input :ifsc,:label=>"IFSC",:placeholder=>"IFSC" %>
        <%= f.input :mobile, :label=>"Mobile", :placeholder=>"Mobile Number Must be 10 Digits" %>
        <%= f.input :address, :label=>"Address",:input_html => { :cols => 50, :rows => 3 } %>
        <%= f.submit 'Save', :disable_with=>'Please wait...' %>
      </fieldset>
  <% end %>
</div>

app/views/accounts/_recent.html.erb
<div class="recent_items">
  <div class="margin">
    <h3>Recent Accounts</h3>
    <% if @recent.blank? %>
        No Accounts Added Yet...
    <% else %>
        <% for account in @recent %>
            <div id="margin">
              <div class="left">&nbsp;</div>
              <div class="right">&nbsp;</div>
              <div class="left-to-right">
                <div class="pen">&nbsp;</div>
                <div class="text">
                  <%= link_to account.name.titleize, account_path(account), :class=>'usuallink tipTipRight',:title => "View Details" %>
                  <div style="margin: 8px 0px;">&nbsp;</div>
                </div>
              </div>
            </div>
        <% end %>
    <% end %>
    <div class="see_all">
      <a href="<%=accounts_path%>">
        View all Accounts
        <img hspace="2" border="0" alt="" src="/images/blue^.gif">
      </a>
    </div>
  </div>
</div>

app/views/accounts/_upload.html.erb
<h4>Please Select the CSV File to import Accounts</h4>
<%= form_tag csv_import_accounts_path, :multipart => true do -%>
    <table class="tablesorter1" align="center">
      <tr>
        <td>
          <label for="vle_user">
            Select a CSV File :
          </label>
        </td>
        <td>
          <%= file_field_tag :file, :id => "filename" -%>
          <script type="text/javascript">
              var filename = new LiveValidation('filename', {
                  onlyOnSubmit:true
              });
              filename.add(Validate.Presence)
          </script>
        </td>
      </tr>
      <tr>
        <td colspan='2' align="right">
          <%= submit_tag 'Submit', :disable_with => 'Please wait...' -%>
        </td>
      </tr>
    </table>
<% end -%>
<style type="text/css">
    table.tablesorter1 {
        border-collapse: collapse;
        border: 1px solid #CDCDCD;
        text-align: center;
    }

    table.tablesorter1 td, table.tablesorter1 th {
        border-collapse: collapse;
        border: 1px solid #CDCDCD;
    }

</style>

app/views/accounts/approve.js.erb
$("#status_<%=@account.id%>").html("<%=escape_javascript(link_to @account.status? ? image_tag('tick.gif') : image_tag('cross.gif'),approve_account_path,:remote=>true)%>");

app/views/accounts/edit.html.erb
<% title "VEDAVAAG | Accounts " %>
<% content_for :sub_heading do %>
    <%= sub_heading('VEDAVAAG | Accounts','Modify Account') %>
<% end %>
<%= render 'form',:heading => 'Create New Account' %>
<div class="link_buttons">
  <%=link_to_all(accounts_path)%>
</div>

app/views/accounts/export.html.erb
<table class="tablesorter">
  <thead>
  <tr>
    <th>#</th>
    <th>Name</th>
    <th>Account</th>
    <th>Bank</th>
    <th>Branch</th>
    <th>Code</th>
  </tr>
  </thead>
  <% i=1 %>
  <% @accounts.each do |tr| %>
      <tr align="left">
        <td><%= i %></td>
        <td><%= tr.name.titleize %></td>
        <td><%= tr.account_number %></td>
        <td><%= tr.bank_name? ? tr.bank_name.upcase : "N.A" %></td>
        <td><%= tr.branch_name? ? tr.branch_name.titleize : "N.A" %></td>
        <td><%= tr.branch_code? ? tr.branch_code : "N.A" %></td>
      </tr>
      <% i = i + 1 %>
  <% end %>
</table>

<style type="text/css">
    table.tablesorter {
        border-collapse: collapse;
        border: 1px solid #000000;
        font-size: 10px;

    }

    table.tablesorter td, table.tablesorter th {
        border-collapse: collapse;
        border: 1px solid #000000;
    }

</style>

app/views/accounts/index.html.erb
<% title "VEDAVAAG | Accounts" %>
<h3>VEDAVAAG | Accounts | Manage Accounts</h3>

<% content_for :left_panel do %>
    <td valign="top" width="250"> <%= render 'common/search' %>
      <%= render 'recent' %> </td>
<% end %>
<div class="help_text">
  Area for managing Accounts. <br/>
  Along with creating, managing Accounts<br/>
</div>
<div class="link_buttons">
  <%= link_to content_tag(:span, 'New Account'), new_account_path, :class => 'btn-blue' %>
  <%= link_to content_tag(:span, 'Accounts Home'), accounts_path, :class => 'btn-yellow' %>

</div>

<div id="new_form">
  <%= render 'upload' %>
</div>
<% if @accounts.blank? %>
    <div class="error_msg">
      OOPS!.. No Accounts are Found in the System..!
    </div>
<% else %>
    <table width="100%">
      <tr>
        <td align="right">
          <b><i>per page</i></b>
          <%= per_page %>| <%= page_entries_info @accounts %>
        </td>
      </tr>
    </table>
    <table class="tablesorter">
      <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Account</th>
        <th>Bank</th>
        <th>Branch</th>
        <th>IFSC</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% i=1 %>
      <% @accounts.each do |account| %>
          <tr>
            <td><%= i %></td>
            <td><%= highlight(account.name.titleize,params[:search]) %></td>
            <td><%= highlight(account.account_number,params[:search]) %></td>
            <td><%= account.bank_name? ? account.bank_name.upcase : "N.A" %></td>
            <td><%= account.branch_name? ? account.branch_name.titleize : "N.A" %></td>
            <td><%= account.ifsc %></td>
            <td>
              <%= link_for_show_pop(account) %>
              <%=  link_for_edit(edit_account_path(account)) %>
              <%= link_for_destroy(account) %>
            </td>
          </tr>
          <% i = i + 1 %>
      <% end %>
      </tbody>
    </table>
    <div class="flickr_pagination">
      <%= page_entries_info @accounts %> <%= will_paginate @accounts, :container => false %>
    </div>
<% end %>

app/views/accounts/new.html.erb
<% title "VEDAVAAG | Accounts " %>
<% content_for :sub_heading do %>
    <%= sub_heading('VEDAVAAG | Accounts','Create Account') %>
<% end %>
<%= render 'form',:heading => 'Create New Account' %>
<div class="link_buttons">
  <%=link_to_all(accounts_path)%>
</div>

app/views/accounts/show.html.erb
<% title "SECC | Account" %>
<div id="page_container">
  <div id="page_content">
    <div class="content">
      <h3>Accounts | View Account Details</h3>

      <table width="100%" border=0 cellspacing=1 cellpadding=3 class="listTable">
        <tr>
          <th width="20%">Name</th>
          <td><%= @account.name %></td>
        </tr>
        <tr>
          <th width="20%">Account</th>
          <td><%= @account.account_number %></td>
        </tr>
        <tr>
          <th width="20%">Bank</th>
          <td><%= @account.bank_name %></td>
        </tr>
        <tr>
          <th width="20%">Branch</th>
          <td><%= @account.branch_name %></td>
        </tr>
        <tr>
          <th width="20%">IFSC</th>
          <td><%= @account.ifsc %></td>
        </tr>
        <tr>
          <th width="20%">Address</th>
          <td><%= @account.address %></td>
        </tr>
      </table>
    </div>
  </div>
</div>